#!/bin/bash
set -e

until PGPASSWORD=$POSTGRES_PASSWORD psql -h "localhost" -U "$POSTGRES_USER" -d "postgres" -c '\q'; do
  echo "Postgres не готов..."
  sleep 2
done

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE ${PROJECT1_DB};
  CREATE USER ${PROJECT1_APP_USER} WITH PASSWORD '${PROJECT1_APP_PASS}';
  GRANT ALL PRIVILEGES ON DATABASE ${PROJECT1_DB} TO ${PROJECT1_APP_USER};
  
  CREATE DATABASE ${PROJECT2_DB};
  CREATE USER ${PROJECT2_APP_USER} WITH PASSWORD '${PROJECT2_APP_PASS}';
  GRANT ALL PRIVILEGES ON DATABASE ${PROJECT2_DB} TO ${PROJECT2_APP_USER};
  
  \c ${PROJECT1_DB}
  GRANT ALL ON SCHEMA public TO ${PROJECT1_APP_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${PROJECT1_APP_USER};
  
  \c ${PROJECT2_DB}
  GRANT ALL ON SCHEMA public TO ${PROJECT2_APP_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${PROJECT2_APP_USER};
EOSQL

echo "✅ Demo БД созданы"
